export const undergraduateMajors = [
  "Advertising, BS",
  "Aerospace Engineering, BS",
  "African American Studies, BA",
  "Animation & Illustration, BFA",
  "Anthropology, BA",
  "Anthropology, BA (SJSU Online)",
  "Applied Mathematics, Applied and Computational Mathematics Concentration, BS",
  "Art History and Visual Culture, BA",
  "Art, Digital Media Art Concentration, BFA",
  "Art, Photography Concentration, BFA",
  "Art, Pictorial Art Concentration, BFA",
  "Art, Spatial Art Concentration, BFA",
  "Art, Studio Practice Concentration (Preparation for Teaching), BA",
  "Art, Studio Practice Concentration, BA",
  "Aviation, BS",
  "Behavioral Science, BA",
  "Biological Sciences - Ecology and Evolution, BS",
  "Biological Sciences - Marine Biology, BS",
  "Biological Sciences, BA",
  "Biological Sciences, Microbiology Concentration, BS",
  "Biological Sciences, Molecular Biology Concentration, BS",
  "Biological Sciences, Systems Physiology Concentration, BS",
  "Biomedical Engineering, BS",
  "Business Administration, Accounting Concentration, BS",
  "Business Administration, Accounting Information Systems Concentration, BS",
  "Business Administration, Business Analytics Concentration, BS",
  "Business Administration, Corporate Accounting and Finance Concentration, BS",
  "Business Administration, Entrepreneurship Concentration, BS",
  "Business Administration, Finance Concentration, BS",
  "Business Administration, General Business Concentration, BS",
  "Business Administration, Hospitality, Tourism and Event Management Concentration, BS",
  "Business Administration, Human Resource Management Concentration, BS",
  "Business Administration, International Business Concentration, BS",
  "Business Administration, Management Concentration, BS",
  "Business Administration, Management Information Systems Concentration, BS",
  "Business Administration, Marketing Concentration, BS",
  "Business Administration, Operations and Supply Chain Management Concentration, BS",
  "Chemical Engineering, BS",
  "Chemistry, BA",
  "Chemistry, Biochemistry Concentration, BS",
  "Chemistry, BS",
  "Chicana and Chicano Studies, BA",
  "Child and Adolescent Development, BA",
  "Child and Adolescent Development, Preparation for Teaching W/CSET Waiver, BA",
  "Child and Adolescent Development, Preparation for Teaching, BA",
  "Chinese, BA",
  "Civil Engineering, BS",
  "Climate Science, BS",
  "Communication Studies, BA",
  "Communication Studies, Preparation for Teaching, BA (Not Accepting Students)",
  "Communicative Disorders and Sciences, BA",
  "Computer Engineering, BS",
  "Computer Science, BS",
  "Computer Science and Linguistics, BS",
  "Creative Arts, BA",
  "Dance, BA",
  "Dance, BFA",
  "Data Science, BS",
  "Design Studies, BA",
  "Earth System Science, BS",
  "Economics, BA",
  "Economics, BA (SJSU Online)",
  "Economics, BS",
  "Electrical Engineering, BS",
  "Engineering Technology, Computer Network System Management Concentration, BS",
  "Engineering Technology, Manufacturing Systems Concentration, BS",
  "English, BA",
  "English, Creative Writing Concentration, BA",
  "English, Preparation for Teaching (Single Subject), BA",
  "English, Professional and Technical Writing Concentration, BA",
  "Environmental Studies, BA",
  "Environmental Studies, BS",
  "Environmental Studies, Preparation for Teaching, BA",
  "Forensic Science, Biology Concentration, BS",
  "Forensic Science, Chemistry Concentration, BS",
  "Forensic Science, Crime Scene Investigation Concentration, BS",
  "Forensic Science, Digital Evidence Concentration, BS",
  "French, BA",
  "French, Preparation for Teaching, BA (Not accepting students)",
  "Geography, BA",
  "Geology, BS",
  "Global Studies, BA",
  "Graphic Design, BFA",
  "History, BA",
  "Humanities, American Studies Concentration, BA",
  "Humanities, Liberal Arts Concentration, BA",
  "Humanities, Religious Studies Concentration, BA",
  "Industrial and Systems Engineering, BS",
  "Industrial Design, BS",
  "Information Science and Data Analytics, BS",
  "Information Science and Data Analytics, BS (SJSU Online)",
  "Interdisciplinary Engineering, BS",
  "Interdisciplinary Engineering, BS (SJSU Online)",
  "Interdisciplinary Studies, BA",
  "Interdisciplinary Studies, BS",
  "Interdisciplinary Studies, Educational and Community Leadership Concentration, BA (SJSU Online)",
  "Interior Design, BFA",
  "Japanese, BA",
  "Journalism, BS",
  "Justice Studies, BS",
  "Justice Studies, Criminology Concentration, BS",
  "Kinesiology, BS",
  "Kinesiology, Preparation for Teaching, BS",
  "Liberal Studies, Integrated Teacher Education Program Spanish Bilingual, BA",
  "Liberal Studies, Integrated Teacher Education Program, BA",
  "Liberal Studies, Preparation for Teaching, BA",
  "Linguistics, BA",
  "Materials Engineering, BS",
  "Mathematics, BA",
  "Mathematics, Integrated Teacher Education Program, BA",
  "Mechanical Engineering, BS",
  "Meteorology, BS",
  "Music, BA",
  "Music, Composition Concentration, BM",
  "Music, Jazz Studies Concentration, BM",
  "Music, Music Education Concentration, BM",
  "Music, Performance Concentration, BM",
  "Nursing, BS",
  "Nursing, Concurrent Enrollment Program (CEP) ADN to BSN",
  "Nursing, RN to BSN Concentration, BS",
  "Nutritional Science, Applied Nutrition and Food Sciences Concentration, BS",
  "Nutritional Science, Dietetics Concentration, BS",
  "Nutritional Science, Food Management Concentration, BS",
  "Organizational Studies, BA",
  "Packaging, BS",
  "Philosophy, BA",
  "Physics, BA",
  "Physics, BS",
  "Physics, Preparation for Teaching, BA",
  "Political Science, BA",
  "Psychology, BA",
  "Psychology, BS",
  "Public Health, BS",
  "Public Health, Concentration in Community Health Education, BS",
  "Public Health, Concentration in Population Data Science, BS",
  "Public Relations, BS",
  "Radio-Television-Film, BA",
  "Recreation, BS",
  "Recreation, Recreation Management Concentration, BS",
  "Recreation, Recreation Therapy Concentration, BS",
  "Social Science, Preparation for Teaching (Single Subject), BA",
  "Social Work, BA",
  "Sociology, BA",
  "Sociology, Community Change Concentration, BA",
  "Sociology, Race and Ethnic Studies Concentration, BA",
  "Sociology, Social Interaction Concentration, BA (Not accepting students)",
  "Sociology, Women, Gender, and Sexuality Studies Concentration, BA",
  "Software Engineering, BS",
  "Spanish, BA",
  "Statistics, BS",
  "Theatre Arts, BA",
];

export const graduateMajors = [
  "Accountancy, MS",
  "Aerospace Engineering, MS",
  "Applied Anthropology, MA",
  "Applied Mathematics, MS",
  "Archives and Records Administration, MARA",
  "Art, Art History and Visual Culture Concentration, MA",
  "Art, Digital Media Art Concentration, MFA",
  "Art, Photography Concentration, MFA",
  "Art, Pictorial Art Concentration, MFA",
  "Art, Spatial Art Concentration, MFA",
  "Artificial Intelligence, MS",
  "Bioinformatics, MS",
  "Biological Sciences, Ecology and Evolution Concentration, MS",
  "Biological Sciences, MA",
  "Biological Sciences, Molecular Biology and Microbiology Concentration, MS",
  "Biological Sciences, Physiology Concentration, MS",
  "Biomedical Engineering, Biomedical Devices Concentration, MS",
  "Biomedical Engineering, MS",
  "Biotechnology, MBT",
  "Business Administration (Early Career), MBA",
  "Business Administration (For Professionals), MBA",
  "Chemical Engineering, MS",
  "Chemistry, MA",
  "Chemistry, MS",
  "Chicana and Chicano Studies, MA",
  "Child and Adolescent Development, MA",
  "Civil Engineering, MS",
  "Clinical Mental Health Counseling, MS",
  "Communication Studies, MA",
  "Computer Engineering, MS",
  "Computer Science, MS",
  "Counseling and Guidance, MA",
  "Creative Writing, MFA",
  "Criminology, Global Criminology Concentration, MS",
  "Data Analytics, MS",
  "Data Science, MS",
  "Economics, Applied Economics Concentration, MA",
  "Economics, MA",
  "Education, Curriculum and Instruction (LACES) Concentration, MA (Not Accepting Students)",
  "Educational Leadership, Concentration in Emancipatory School Leadership, MA",
  "Electrical Engineering, MS",
  "Engineering Management, MS",
  "Engineering Technology, MS",
  "Engineering, Electronic Materials and Devices Concentration, MS (Not Accepting Students)",
  "Engineering, MS",
  "English, MA",
  "Environmental Studies, MS",
  "Geography, MA",
  "Geology, MS",
  "Higher Education Leadership, MA",
  "History, MA",
  "Human Factors/Ergonomics, MS",
  "Human Factors/Ergonomics, User Experience Concentration, MS",
  "Industrial and Systems Engineering, MS",
  "Informatics, MS",
  "Interdisciplinary Studies, MA",
  "Interdisciplinary Studies, MS",
  "Justice Studies, MS",
  "Kinesiology, MS",
  "Library and Information Science, MLIS",
  "Linguistics, MA",
  "Marine Science, MS",
  "Mass Communications, MS",
  "Materials Engineering, MS",
  "Mathematics, MA",
  "Mechanical Engineering, MS",
  "Medical Product Development Management, MS",
  "Meteorology, MS",
  "Music Education, MA",
  "Music, MM",
  "Nursing, Family Nurse Practitioner Concentration, MS",
  "Nursing, MS",
  "Nutritional Science, MS",
  "Occupational Therapy, MS",
  "Philosophy, MA",
  "Physics, MS",
  "Psychology, Industrial/Organizational Psychology Concentration, MS",
  "Psychology, Research and Experimental Psychology Concentration, MA",
  "Public Administration, MPA",
  "Public Health, MPH",
  "Recreation, International Tourism Concentration, MS (Not Accepting Students)",
  "Recreation, MS",
  "Science Education, MS",
  "Social Work, MSW",
  "Software Engineering, MS",
  "Spanish, MA",
  "Special Education, MA",
  "Speech Language Pathology, MS",
  "Statistics, MS",
  "Taxation, MS",
  "Teaching English to Speakers of Other Languages (TESOL), MA",
  "Teaching, Critical Bilingual Education (Spanish) Concentration, MAT",
  "Teaching, MAT",
  "Transportation Management, MS",
  "Urban Planning, MUP",
];
